# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Core.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(957, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.BackgroundFrame = QtWidgets.QFrame(self.centralwidget)
        self.BackgroundFrame.setStyleSheet("#BackgroundFrame{\n"
"   /*border-top: 1px solid black; \n"
"   border-bottom: 1px solid black; \n"
"   border-right: 1px solid black;\n"
"   border-left: 1px solid black;\n"
"   border-radius: 5px;\n"
"   border-color: rgb(0, 120, 215);*/\n"
"   margin: -1px;\n"
"}")
        self.BackgroundFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BackgroundFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BackgroundFrame.setObjectName("BackgroundFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.BackgroundFrame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MenuBar = QtWidgets.QWidget(self.BackgroundFrame)
        self.MenuBar.setStyleSheet("#MenuBar{\n"
"   background-color: #ffffff;\n"
"   /*border: none;\n"
"   border-right: 1px solid white; */\n"
"   border-top-left-radius: 5px;\n"
"   border-bottom-left-radius: 5px;\n"
"}\n"
"\n"
"QFrame{\n"
"   background-color: rgb(0, 120, 215);\n"
"}\n"
"\n"
"QWidget{\n"
"    background-color: rgb(0, 120, 215);\n"
"}")
        self.MenuBar.setObjectName("MenuBar")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.MenuBar)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TitleSection = QtWidgets.QWidget(self.MenuBar)
        self.TitleSection.setStyleSheet("QWidget{\n"
"    /*border-top-left-radius: 5px;*/\n"
"}")
        self.TitleSection.setObjectName("TitleSection")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.TitleSection)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.TitleContainer = QtWidgets.QWidget(self.TitleSection)
        self.TitleContainer.setObjectName("TitleContainer")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.TitleContainer)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.TitleButton = QtWidgets.QPushButton(self.TitleContainer)
        self.TitleButton.setStyleSheet("#TitleButton{\n"
"   background-color: none;\n"
"   border-radius: none;\n"
"   padding: 0px;\n"
"   margin: 4px;\n"
"   margin-top: 8px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/Icons/apeW.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.TitleButton.setIcon(icon)
        self.TitleButton.setIconSize(QtCore.QSize(27, 27))
        self.TitleButton.setObjectName("TitleButton")
        self.gridLayout_6.addWidget(self.TitleButton, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.TitleContainer, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.verticalLayout_2.addWidget(self.TitleSection, 0, QtCore.Qt.AlignTop)
        self.ContentSection = QtWidgets.QWidget(self.MenuBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContentSection.sizePolicy().hasHeightForWidth())
        self.ContentSection.setSizePolicy(sizePolicy)
        self.ContentSection.setStyleSheet("QPushButton{\n"
"    border-radius: none;\n"
"    background-color: none;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    background-color: rgb(0, 108, 190);\n"
"}\n"
"\n"
"#ContentSection{\n"
"    border-radius: none;\n"
"    background-color: none;\n"
"}")
        self.ContentSection.setObjectName("ContentSection")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ContentSection)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.TopSpaceFrame = QtWidgets.QFrame(self.ContentSection)
        self.TopSpaceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopSpaceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopSpaceFrame.setObjectName("TopSpaceFrame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.TopSpaceFrame)
        self.gridLayout_18.setContentsMargins(0, 20, 0, 10)
        self.gridLayout_18.setSpacing(0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        spacerItem = QtWidgets.QSpacerItem(20, 175, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_18.addItem(spacerItem, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.TopSpaceFrame)
        self.VideoPageFrame = QtWidgets.QFrame(self.ContentSection)
        self.VideoPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoPageFrame.setObjectName("VideoPageFrame")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.VideoPageFrame)
        self.gridLayout_14.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_14.setSpacing(0)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.verticalLayout_4.addWidget(self.VideoPageFrame)
        self.ModelPageFrame = QtWidgets.QFrame(self.ContentSection)
        self.ModelPageFrame.setStyleSheet("")
        self.ModelPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ModelPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ModelPageFrame.setObjectName("ModelPageFrame")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.ModelPageFrame)
        self.gridLayout_15.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_4.addWidget(self.ModelPageFrame)
        self.FinalPageFrame = QtWidgets.QFrame(self.ContentSection)
        self.FinalPageFrame.setStyleSheet("")
        self.FinalPageFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FinalPageFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FinalPageFrame.setObjectName("FinalPageFrame")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.FinalPageFrame)
        self.gridLayout_16.setContentsMargins(0, 10, 0, 10)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.verticalLayout_4.addWidget(self.FinalPageFrame)
        self.BottomSpaceFrame = QtWidgets.QFrame(self.ContentSection)
        self.BottomSpaceFrame.setStyleSheet("")
        self.BottomSpaceFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BottomSpaceFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BottomSpaceFrame.setObjectName("BottomSpaceFrame")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.BottomSpaceFrame)
        self.gridLayout_19.setContentsMargins(0, 10, 0, 20)
        self.gridLayout_19.setSpacing(0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        spacerItem1 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_19.addItem(spacerItem1, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.BottomSpaceFrame)
        self.verticalLayout_2.addWidget(self.ContentSection)
        self.BottomSection = QtWidgets.QWidget(self.MenuBar)
        self.BottomSection.setStyleSheet("#BottomSection{\n"
"    /*border-bottom-left-radius: 5px;*/\n"
"}")
        self.BottomSection.setObjectName("BottomSection")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.BottomSection)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.SettingsBtn = QtWidgets.QPushButton(self.BottomSection)
        self.SettingsBtn.setStyleSheet("#SettingsBtn{\n"
"    background-color: none;\n"
"    border-radius: none;\n"
"    padding: 0px;\n"
"    margin: 4px;\n"
"    margin-top: 8px;\n"
"    margin-bottom: 8px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/Icons/settingH.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsBtn.setIcon(icon1)
        self.SettingsBtn.setIconSize(QtCore.QSize(24, 24))
        self.SettingsBtn.setObjectName("SettingsBtn")
        self.gridLayout_17.addWidget(self.SettingsBtn, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.BottomSection)
        self.horizontalLayout.addWidget(self.MenuBar, 0, QtCore.Qt.AlignLeft)
        self.MainWidget = QtWidgets.QWidget(self.BackgroundFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainWidget.sizePolicy().hasHeightForWidth())
        self.MainWidget.setSizePolicy(sizePolicy)
        self.MainWidget.setStyleSheet("#MainWidget{\n"
"   border-top-right-radius: 5px;\n"
"   border-bottom-right-radius: 5px\n"
"}")
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleBar = QtWidgets.QWidget(self.MainWidget)
        self.TitleBar.setStyleSheet("#TitleBar{\n"
"   background-color: rgb(255, 255, 255);\n"
"   border-top-right-radius: 5px;\n"
"}")
        self.TitleBar.setObjectName("TitleBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TitleBar)
        self.horizontalLayout_2.setContentsMargins(7, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TitleNameContainer = QtWidgets.QWidget(self.TitleBar)
        self.TitleNameContainer.setMinimumSize(QtCore.QSize(350, 0))
        self.TitleNameContainer.setStyleSheet("#TitleNameContainer\n"
"{\n"
"}")
        self.TitleNameContainer.setObjectName("TitleNameContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.TitleNameContainer)
        self.horizontalLayout_4.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.DAPE_3 = QtWidgets.QLabel(self.TitleNameContainer)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.DAPE_3.setFont(font)
        self.DAPE_3.setStyleSheet("#DAPE_3{\n"
"    color: rgb(100, 100, 100);\n"
"}")
        self.DAPE_3.setObjectName("DAPE_3")
        self.horizontalLayout_4.addWidget(self.DAPE_3)
        self.PathTitle = QtWidgets.QLineEdit(self.TitleNameContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PathTitle.sizePolicy().hasHeightForWidth())
        self.PathTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.PathTitle.setFont(font)
        self.PathTitle.setStyleSheet("#PathTitle{\n"
"    color: rgb(100, 100, 100);\n"
"}\n"
"")
        self.PathTitle.setMaxLength(30)
        self.PathTitle.setFrame(False)
        self.PathTitle.setObjectName("PathTitle")
        self.horizontalLayout_4.addWidget(self.PathTitle)
        self.horizontalLayout_2.addWidget(self.TitleNameContainer, 0, QtCore.Qt.AlignLeft)
        self.ButtonContainer = QtWidgets.QWidget(self.TitleBar)
        self.ButtonContainer.setStyleSheet("QPushButton{\n"
"   color: rgb(0, 0, 0);\n"
"   border-radius: none;\n"
"}\n"
"QPushButton:hover{\n"
"   background-color: rgb(0, 120, 215);\n"
"}\n"
"#CloseButton{\n"
"   /*border-top-right-radius: 5px;*/\n"
"} \n"
"#CloseButton:hover{\n"
"   background-color: rgb(170, 0, 0);\n"
"}")
        self.ButtonContainer.setObjectName("ButtonContainer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ButtonContainer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MinContainer = QtWidgets.QWidget(self.ButtonContainer)
        self.MinContainer.setObjectName("MinContainer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MinContainer)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.MinimizeButton = QtWidgets.QPushButton(self.MinContainer)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/Icons/minusB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MinimizeButton.setIcon(icon2)
        self.MinimizeButton.setIconSize(QtCore.QSize(41, 27))
        self.MinimizeButton.setObjectName("MinimizeButton")
        self.gridLayout_2.addWidget(self.MinimizeButton, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.MinContainer)
        self.MaxContainer = QtWidgets.QWidget(self.ButtonContainer)
        self.MaxContainer.setObjectName("MaxContainer")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.MaxContainer)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.MaximizeButton = QtWidgets.QPushButton(self.MaxContainer)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI/Icons/maximizeB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MaximizeButton.setIcon(icon3)
        self.MaximizeButton.setIconSize(QtCore.QSize(41, 28))
        self.MaximizeButton.setObjectName("MaximizeButton")
        self.gridLayout_3.addWidget(self.MaximizeButton, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.MaxContainer)
        self.CloseContainer = QtWidgets.QWidget(self.ButtonContainer)
        self.CloseContainer.setObjectName("CloseContainer")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.CloseContainer)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.CloseButton = QtWidgets.QPushButton(self.CloseContainer)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI/Icons/closeB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CloseButton.setIcon(icon4)
        self.CloseButton.setIconSize(QtCore.QSize(41, 28))
        self.CloseButton.setObjectName("CloseButton")
        self.gridLayout_4.addWidget(self.CloseButton, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.CloseContainer)
        self.horizontalLayout_2.addWidget(self.ButtonContainer, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.TitleBar, 0, QtCore.Qt.AlignTop)
        self.Content = QtWidgets.QWidget(self.MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Content.sizePolicy().hasHeightForWidth())
        self.Content.setSizePolicy(sizePolicy)
        self.Content.setStyleSheet("#Content{\n"
"   border-bottom-right-radius: 5px;\n"
"   background-color: #ffffff;\n"
"}")
        self.Content.setObjectName("Content")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Content)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.Content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.VideoPage = QtWidgets.QWidget()
        self.VideoPage.setStyleSheet("")
        self.VideoPage.setObjectName("VideoPage")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.VideoPage)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.VidPageBackground = QtWidgets.QWidget(self.VideoPage)
        self.VidPageBackground.setObjectName("VidPageBackground")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.VidPageBackground)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.VideoSplitter = QtWidgets.QSplitter(self.VidPageBackground)
        self.VideoSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.VideoSplitter.setHandleWidth(0)
        self.VideoSplitter.setObjectName("VideoSplitter")
        self.VideoBox = QtWidgets.QFrame(self.VideoSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoBox.sizePolicy().hasHeightForWidth())
        self.VideoBox.setSizePolicy(sizePolicy)
        self.VideoBox.setMinimumSize(QtCore.QSize(640, 0))
        self.VideoBox.setSizeIncrement(QtCore.QSize(1, 0))
        self.VideoBox.setObjectName("VideoBox")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.VideoBox)
        self.gridLayout_11.setContentsMargins(-1, -1, 6, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.VideoFrame = QtWidgets.QFrame(self.VideoBox)
        self.VideoFrame.setStyleSheet("#VideoFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 5px;\n"
"}")
        self.VideoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoFrame.setObjectName("VideoFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.VideoFrame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.VideoContainer = QtWidgets.QWidget(self.VideoFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoContainer.sizePolicy().hasHeightForWidth())
        self.VideoContainer.setSizePolicy(sizePolicy)
        self.VideoContainer.setObjectName("VideoContainer")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.VideoContainer)
        self.gridLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ImportVidbtn = QtWidgets.QPushButton(self.VideoContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImportVidbtn.sizePolicy().hasHeightForWidth())
        self.ImportVidbtn.setSizePolicy(sizePolicy)
        self.ImportVidbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImportVidbtn.setStyleSheet("#ImportVidbtn{\n"
"    border-radius: 5px;\n"
"    border: 1px solid gray;\n"
"    margin: 20px;\n"
"}")
        self.ImportVidbtn.setObjectName("ImportVidbtn")
        self.gridLayout_9.addWidget(self.ImportVidbtn, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.VideoContainer)
        self.VideoTools = QtWidgets.QWidget(self.VideoFrame)
        self.VideoTools.setStyleSheet("QPushButton{\n"
"    border-radius: none;\n"
"}")
        self.VideoTools.setObjectName("VideoTools")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.VideoTools)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.ToolsContainer = QtWidgets.QFrame(self.VideoTools)
        self.ToolsContainer.setStyleSheet("#ToolsContainer{\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-radius: 5px;\n"
"}")
        self.ToolsContainer.setObjectName("ToolsContainer")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ToolsContainer)
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.PreviousFrame = QtWidgets.QPushButton(self.ToolsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviousFrame.sizePolicy().hasHeightForWidth())
        self.PreviousFrame.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("UI/Icons/previousBu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PreviousFrame.setIcon(icon5)
        self.PreviousFrame.setObjectName("PreviousFrame")
        self.horizontalLayout_5.addWidget(self.PreviousFrame)
        self.PlaynPause = QtWidgets.QPushButton(self.ToolsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlaynPause.sizePolicy().hasHeightForWidth())
        self.PlaynPause.setSizePolicy(sizePolicy)
        self.PlaynPause.setObjectName("PlaynPause")
        self.horizontalLayout_5.addWidget(self.PlaynPause)
        self.NextFrame = QtWidgets.QPushButton(self.ToolsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NextFrame.sizePolicy().hasHeightForWidth())
        self.NextFrame.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("UI/Icons/nextBu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NextFrame.setIcon(icon6)
        self.NextFrame.setObjectName("NextFrame")
        self.horizontalLayout_5.addWidget(self.NextFrame)
        self.horizontalSlider = QtWidgets.QSlider(self.ToolsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setStyleSheet("QSlider{\n"
"    margin-top: 0px;\n"
"    margin-bottom: 0px;\n"
"    margin-right: 5px;\n"
"    margin-left: 5px;\n"
"}\n"
"                                          \n"
"QSlider::groove{                                            \n"
"   border-radius: 1px;\n"
"   height: 3px;\n"
"   margin: 0px;\n"
"   background-color: rgb(100, 100, 100);\n"
"}\n"
"\n"
"QSlider::handle{\n"
"   border: none;\n"
"   height: 10px;\n"
"   width: 10px;\n"
"   margin: -4px;\n"
"   border-radius: 5px;\n"
"   background-color: rgb(0, 120, 215);\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_5.addWidget(self.horizontalSlider)
        self.PreviewBtn = QtWidgets.QPushButton(self.ToolsContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PreviewBtn.sizePolicy().hasHeightForWidth())
        self.PreviewBtn.setSizePolicy(sizePolicy)
        self.PreviewBtn.setStyleSheet("#PreviewBtn{\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 120, 215);\n"
"    background-color: rgb(0, 120, 215);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"#PreviewBtn::hover{\n"
"    background-color:rgb(0, 108, 190);\n"
"    border-color:  rgb(0, 120, 215);\n"
"}\n"
"\n"
"#PreviewBtn::selected{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.PreviewBtn.setObjectName("PreviewBtn")
        self.horizontalLayout_5.addWidget(self.PreviewBtn)
        self.gridLayout_12.addWidget(self.ToolsContainer, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.VideoTools)
        self.gridLayout_11.addWidget(self.VideoFrame, 0, 0, 1, 1)
        self.VidToolBox = QtWidgets.QFrame(self.VideoSplitter)
        self.VidToolBox.setObjectName("VidToolBox")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.VidToolBox)
        self.gridLayout_24.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_24.setSpacing(0)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.VideoOptions = QtWidgets.QWidget(self.VidToolBox)
        self.VideoOptions.setStyleSheet("#VideoOptions{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-left: 1px solid gray;\n"
"    border-color: rgb(217, 217, 217);\n"
"    border-bottom-right-radius: 5px;\n"
"}")
        self.VideoOptions.setObjectName("VideoOptions")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.VideoOptions)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.VideoOptionTab = QtWidgets.QTabWidget(self.VideoOptions)
        self.VideoOptionTab.setDocumentMode(True)
        self.VideoOptionTab.setMovable(True)
        self.VideoOptionTab.setObjectName("VideoOptionTab")
        self.VideoFilesTab = QtWidgets.QWidget()
        self.VideoFilesTab.setObjectName("VideoFilesTab")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.VideoFilesTab)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.VideoScrollArea = QtWidgets.QScrollArea(self.VideoFilesTab)
        self.VideoScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VideoScrollArea.setWidgetResizable(True)
        self.VideoScrollArea.setObjectName("VideoScrollArea")
        self.VideoScrollContent = QtWidgets.QWidget()
        self.VideoScrollContent.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.VideoScrollContent.setStyleSheet("#VideoScrollContent\n"
"{\n"
"    background-color: #ffffff;\n"
"}")
        self.VideoScrollContent.setObjectName("VideoScrollContent")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.VideoScrollContent)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.VideoDetailContainer = QtWidgets.QFrame(self.VideoScrollContent)
        self.VideoDetailContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.VideoDetailContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.VideoDetailContainer.setObjectName("VideoDetailContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.VideoDetailContainer)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5.addWidget(self.VideoDetailContainer, 0, QtCore.Qt.AlignTop)
        self.VideoScrollArea.setWidget(self.VideoScrollContent)
        self.gridLayout_27.addWidget(self.VideoScrollArea, 0, 0, 1, 1)
        self.VideoImportSection = QtWidgets.QWidget(self.VideoFilesTab)
        self.VideoImportSection.setObjectName("VideoImportSection")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.VideoImportSection)
        self.horizontalLayout_6.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.VideoImportBtn = QtWidgets.QPushButton(self.VideoImportSection)
        self.VideoImportBtn.setStyleSheet("#VideoImportBtn{\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 120, 215);\n"
"    background-color: rgb(0, 120, 215);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"#VideoImportBtn::hover{\n"
"    background-color:rgb(0, 108, 190);\n"
"    border-color:  rgb(0, 120, 215);\n"
"}\n"
"\n"
"#VideoImportBtn::selected{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.VideoImportBtn.setObjectName("VideoImportBtn")
        self.horizontalLayout_6.addWidget(self.VideoImportBtn)
        self.gridLayout_27.addWidget(self.VideoImportSection, 1, 0, 1, 1)
        self.VideoOptionTab.addTab(self.VideoFilesTab, "")
        self.VideoEditTab = QtWidgets.QWidget()
        self.VideoEditTab.setObjectName("VideoEditTab")
        self.VideoOptionTab.addTab(self.VideoEditTab, "")
        self.gridLayout_13.addWidget(self.VideoOptionTab, 0, 0, 1, 1)
        self.gridLayout_24.addWidget(self.VideoOptions, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.VideoSplitter, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.VidPageBackground, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.VideoPage)
        self.ModelPage = QtWidgets.QWidget()
        self.ModelPage.setObjectName("ModelPage")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.ModelPage)
        self.gridLayout_21.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_21.setSpacing(0)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.ModelPageBackground = QtWidgets.QWidget(self.ModelPage)
        self.ModelPageBackground.setObjectName("ModelPageBackground")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.ModelPageBackground)
        self.gridLayout_20.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.ModelSplitter = QtWidgets.QSplitter(self.ModelPageBackground)
        self.ModelSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.ModelSplitter.setHandleWidth(0)
        self.ModelSplitter.setObjectName("ModelSplitter")
        self.ModelBox = QtWidgets.QFrame(self.ModelSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelBox.sizePolicy().hasHeightForWidth())
        self.ModelBox.setSizePolicy(sizePolicy)
        self.ModelBox.setMinimumSize(QtCore.QSize(640, 0))
        self.ModelBox.setSizeIncrement(QtCore.QSize(1, 0))
        self.ModelBox.setStyleSheet("")
        self.ModelBox.setObjectName("ModelBox")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.ModelBox)
        self.gridLayout_22.setContentsMargins(-1, -1, 6, -1)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.ModelFrame = QtWidgets.QFrame(self.ModelBox)
        self.ModelFrame.setStyleSheet("QFrame{\n"
"    border-radius: 5px;\n"
"    background-color: #ffffff;\n"
"}")
        self.ModelFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ModelFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ModelFrame.setObjectName("ModelFrame")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.ModelFrame)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setSpacing(0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.ModelContainer = QtWidgets.QWidget(self.ModelFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ModelContainer.sizePolicy().hasHeightForWidth())
        self.ModelContainer.setSizePolicy(sizePolicy)
        self.ModelContainer.setObjectName("ModelContainer")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.ModelContainer)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.ImportModelBtn = QtWidgets.QPushButton(self.ModelContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ImportModelBtn.sizePolicy().hasHeightForWidth())
        self.ImportModelBtn.setSizePolicy(sizePolicy)
        self.ImportModelBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ImportModelBtn.setStyleSheet("#ImportModelBtn{\n"
"    border-radius: 5px;\n"
"    border-color: #0078d7;\n"
"    border: 1px solid gray;\n"
"    margin: 20px;\n"
"}")
        self.ImportModelBtn.setObjectName("ImportModelBtn")
        self.gridLayout_25.addWidget(self.ImportModelBtn, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.ModelContainer, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.ModelFrame, 0, 0, 1, 1)
        self.ModToolBox = QtWidgets.QFrame(self.ModelSplitter)
        self.ModToolBox.setObjectName("ModToolBox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.ModToolBox)
        self.gridLayout_23.setContentsMargins(5, 0, 0, 0)
        self.gridLayout_23.setSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.ModelOptions = QtWidgets.QWidget(self.ModToolBox)
        self.ModelOptions.setStyleSheet("#ModelOptions{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-left: 1px solid gray;\n"
"    border-color: rgb(217, 217, 217);\n"
"    border-bottom-right-radius: 5px;\n"
"}")
        self.ModelOptions.setObjectName("ModelOptions")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.ModelOptions)
        self.gridLayout_29.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_29.setSpacing(0)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.ModelOptionTab = QtWidgets.QTabWidget(self.ModelOptions)
        self.ModelOptionTab.setDocumentMode(True)
        self.ModelOptionTab.setMovable(True)
        self.ModelOptionTab.setObjectName("ModelOptionTab")
        self.ModelEditTab = QtWidgets.QWidget()
        self.ModelEditTab.setObjectName("ModelEditTab")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.ModelEditTab)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.ModelAnimateSection = QtWidgets.QWidget(self.ModelEditTab)
        self.ModelAnimateSection.setObjectName("ModelAnimateSection")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.ModelAnimateSection)
        self.horizontalLayout_8.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ModelAnimateBtn = QtWidgets.QPushButton(self.ModelAnimateSection)
        self.ModelAnimateBtn.setStyleSheet("#ModelAnimateBtn{\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 120, 215);\n"
"    background-color: rgb(0, 120, 215);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"#ModelAnimateBtn::hover{\n"
"    background-color:rgb(0, 108, 190);\n"
"    border-color:  rgb(0, 120, 215);\n"
"}\n"
"\n"
"#ModelAnimateBtn::selected{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ModelAnimateBtn.setObjectName("ModelAnimateBtn")
        self.horizontalLayout_8.addWidget(self.ModelAnimateBtn)
        self.gridLayout_30.addWidget(self.ModelAnimateSection, 1, 0, 1, 1)
        self.BoneSelectionArea = QtWidgets.QScrollArea(self.ModelEditTab)
        self.BoneSelectionArea.setWidgetResizable(True)
        self.BoneSelectionArea.setObjectName("BoneSelectionArea")
        self.BoneSelectionContents = QtWidgets.QWidget()
        self.BoneSelectionContents.setGeometry(QtCore.QRect(0, 0, 251, 498))
        self.BoneSelectionContents.setObjectName("BoneSelectionContents")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.BoneSelectionContents)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BoneMPList = QtWidgets.QFrame(self.BoneSelectionContents)
        self.BoneMPList.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.BoneMPList.setFrameShadow(QtWidgets.QFrame.Raised)
        self.BoneMPList.setObjectName("BoneMPList")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.BoneMPList)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_9.addWidget(self.BoneMPList)
        self.BoneMidLine = QtWidgets.QFrame(self.BoneSelectionContents)
        self.BoneMidLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.BoneMidLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BoneMidLine.setObjectName("BoneMidLine")
        self.horizontalLayout_9.addWidget(self.BoneMidLine)
        self.BoneModelList = QtWidgets.QFrame(self.BoneSelectionContents)
        self.BoneModelList.setObjectName("BoneModelList")
        self.horizontalLayout_9.addWidget(self.BoneModelList)
        self.BoneSelectionArea.setWidget(self.BoneSelectionContents)
        self.gridLayout_30.addWidget(self.BoneSelectionArea, 0, 0, 1, 1)
        self.ModelOptionTab.addTab(self.ModelEditTab, "")
        self.ModelFilesTab = QtWidgets.QWidget()
        self.ModelFilesTab.setObjectName("ModelFilesTab")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.ModelFilesTab)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.ModelScrollArea = QtWidgets.QScrollArea(self.ModelFilesTab)
        self.ModelScrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ModelScrollArea.setWidgetResizable(True)
        self.ModelScrollArea.setObjectName("ModelScrollArea")
        self.ModelScrollContent = QtWidgets.QWidget()
        self.ModelScrollContent.setGeometry(QtCore.QRect(0, 0, 253, 500))
        self.ModelScrollContent.setStyleSheet("#ModelScrollContent\n"
"{\n"
"    background-color: #ffffff;\n"
"}")
        self.ModelScrollContent.setObjectName("ModelScrollContent")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ModelScrollContent)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ModelDetailContainer = QtWidgets.QFrame(self.ModelScrollContent)
        self.ModelDetailContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ModelDetailContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ModelDetailContainer.setObjectName("ModelDetailContainer")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.ModelDetailContainer)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_7.addWidget(self.ModelDetailContainer, 0, QtCore.Qt.AlignTop)
        self.ModelScrollArea.setWidget(self.ModelScrollContent)
        self.gridLayout_28.addWidget(self.ModelScrollArea, 0, 0, 1, 1)
        self.ModelImportSection = QtWidgets.QWidget(self.ModelFilesTab)
        self.ModelImportSection.setObjectName("ModelImportSection")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.ModelImportSection)
        self.horizontalLayout_7.setContentsMargins(15, 0, 15, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ModelImportBtn = QtWidgets.QPushButton(self.ModelImportSection)
        self.ModelImportBtn.setStyleSheet("#ModelImportBtn{\n"
"    border: 1px solid gray;\n"
"    border-radius: 10px;\n"
"    border-color: rgb(0, 120, 215);\n"
"    background-color: rgb(0, 120, 215);\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 5px;\n"
"    padding-left: 15px;\n"
"    padding-right: 15px;\n"
"}\n"
"\n"
"#ModelImportBtn::hover{\n"
"    background-color:rgb(0, 108, 190);\n"
"    border-color:  rgb(0, 120, 215);\n"
"}\n"
"\n"
"#ModelImportBtn::selected{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.ModelImportBtn.setObjectName("ModelImportBtn")
        self.horizontalLayout_7.addWidget(self.ModelImportBtn)
        self.gridLayout_28.addWidget(self.ModelImportSection, 1, 0, 1, 1)
        self.ModelOptionTab.addTab(self.ModelFilesTab, "")
        self.gridLayout_29.addWidget(self.ModelOptionTab, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.ModelOptions, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.ModelSplitter, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.ModelPageBackground, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.ModelPage)
        self.FinalPage = QtWidgets.QWidget()
        self.FinalPage.setObjectName("FinalPage")
        self.ExportModelBtn = QtWidgets.QPushButton(self.FinalPage)
        self.ExportModelBtn.setEnabled(False)
        self.ExportModelBtn.setGeometry(QtCore.QRect(360, 230, 75, 23))
        self.ExportModelBtn.setObjectName("ExportModelBtn")
        self.stackedWidget.addWidget(self.FinalPage)
        self.gridLayout_7.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.Content)
        self.horizontalLayout.addWidget(self.MainWidget)
        self.gridLayout.addWidget(self.BackgroundFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.VideoOptionTab.setCurrentIndex(1)
        self.ModelOptionTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "3DAPE"))
        self.DAPE_3.setText(_translate("MainWindow", "3DAPE \\"))
        self.PathTitle.setText(_translate("MainWindow", "Video-Preview :"))
        self.ImportVidbtn.setText(_translate("MainWindow", "Import Video"))
        self.PreviewBtn.setText(_translate("MainWindow", "Preview"))
        self.VideoImportBtn.setText(_translate("MainWindow", "Import Video"))
        self.VideoOptionTab.setTabText(self.VideoOptionTab.indexOf(self.VideoFilesTab), _translate("MainWindow", "Videos"))
        self.VideoOptionTab.setTabText(self.VideoOptionTab.indexOf(self.VideoEditTab), _translate("MainWindow", "Edit"))
        self.ImportModelBtn.setText(_translate("MainWindow", "Import Model"))
        self.ModelAnimateBtn.setText(_translate("MainWindow", "Animate"))
        self.ModelOptionTab.setTabText(self.ModelOptionTab.indexOf(self.ModelEditTab), _translate("MainWindow", "Animate"))
        self.ModelImportBtn.setText(_translate("MainWindow", "Animate"))
        self.ModelOptionTab.setTabText(self.ModelOptionTab.indexOf(self.ModelFilesTab), _translate("MainWindow", "Model"))
        self.ExportModelBtn.setText(_translate("MainWindow", "Export"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
