# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mapping.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MappingWidget(object):
    def setupUi(self, MappingWidget):
        MappingWidget.setObjectName("MappingWidget")
        MappingWidget.resize(150, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(MappingWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MPBoneName = QtWidgets.QLabel(MappingWidget)
        self.MPBoneName.setObjectName("MPBoneName")
        self.horizontalLayout.addWidget(self.MPBoneName)
        self.ModelBoneBtn = QtWidgets.QPushButton(MappingWidget)
        self.ModelBoneBtn.setObjectName("ModelBoneBtn")
        self.horizontalLayout.addWidget(self.ModelBoneBtn)

        self.retranslateUi(MappingWidget)
        QtCore.QMetaObject.connectSlotsByName(MappingWidget)

    def retranslateUi(self, MappingWidget):
        _translate = QtCore.QCoreApplication.translate
        MappingWidget.setWindowTitle(_translate("MappingWidget", "Form"))
        self.MPBoneName.setText(_translate("MappingWidget", "BoneName"))
        self.ModelBoneBtn.setText(_translate("MappingWidget", "Bone"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MappingWidget = QtWidgets.QWidget()
    ui = Ui_MappingWidget()
    ui.setupUi(MappingWidget)
    MappingWidget.show()
    sys.exit(app.exec_())
