# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Import.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class QtImportDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")

        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        Dialog.resize(800, 200)
        Dialog.setStyleSheet("#MainWidget{\n"
"   background-color: #2e2d2f;\n"
"   border:1px solid gray;\n"
"}\n"
"\n"
"#Title{\n"
"   color: #fbfdfb;\n"
"}\n"
"\n"
"#TypeLabel{\n"
"   color: rgb(175, 175, 175);\n"
"}\n"
"\n"
"#FileLabel{\n"
"   color: rgb(175, 175, 175);\n"
"}\n")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainWidget = QtWidgets.QWidget(Dialog)
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleWidget = QtWidgets.QWidget(self.MainWidget)
        self.TitleWidget.setObjectName("TitleWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TitleWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Title = QtWidgets.QLabel(self.TitleWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.gridLayout_3.addWidget(self.Title, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.TitleWidget, 0, QtCore.Qt.AlignTop)
        self.ContentWidget = QtWidgets.QWidget(self.MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContentWidget.sizePolicy().hasHeightForWidth())
        self.ContentWidget.setSizePolicy(sizePolicy)
        self.ContentWidget.setObjectName("ContentWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContentWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.TypeWidget = QtWidgets.QWidget(self.ContentWidget)
        self.TypeWidget.setObjectName("TypeWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.TypeWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.TypeLabel = QtWidgets.QLabel(self.TypeWidget)
        self.TypeLabel.setObjectName("TypeLabel")
        self.horizontalLayout_2.addWidget(self.TypeLabel)
        self.comboBox = QtWidgets.QComboBox(self.TypeWidget)
        self.comboBox.addItem("FullBody") 
        self.comboBox.addItem("Face") 
        self.comboBox.addItem("Fingers")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalLayout.addWidget(self.TypeWidget)
        self.FileWidget = QtWidgets.QWidget(self.ContentWidget)
        self.FileWidget.setObjectName("FileWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.FileWidget)
        self.horizontalLayout_3.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FileLabel = QtWidgets.QLabel(self.FileWidget)
        self.FileLabel.setObjectName("FileLabel")
        self.horizontalLayout_3.addWidget(self.FileLabel)
        self.lineEdit = QtWidgets.QLineEdit(self.FileWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.BrowseBtn = QtWidgets.QPushButton(self.FileWidget)
        self.BrowseBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/Icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BrowseBtn.setIcon(icon)
        self.BrowseBtn.setIconSize(QtCore.QSize(18, 18))
        self.BrowseBtn.setFlat(True)
        self.BrowseBtn.setObjectName("BrowseBtn")
        self.horizontalLayout_3.addWidget(self.BrowseBtn)
        self.horizontalLayout.addWidget(self.FileWidget)
        self.verticalLayout.addWidget(self.ContentWidget)
        self.ConfirmWidget = QtWidgets.QWidget(self.MainWidget)
        self.ConfirmWidget.setObjectName("ConfirmWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ConfirmWidget)
        self.gridLayout_2.setContentsMargins(-1, 0, -1, 3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.ConfirmWidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.ConfirmWidget, 0, QtCore.Qt.AlignBottom)
        self.gridLayout.addWidget(self.MainWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        self.Title.setText(_translate("Dialog", "Import Video File"))
        self.TypeLabel.setText(_translate("Dialog", "Type :"))
        self.FileLabel.setText(_translate("Dialog", "File : "))
        self.lineEdit.setText(_translate("Dialog", "Path"))



class QtProgressDialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")

        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        
        Dialog.resize(500, 120)
        Dialog.setStyleSheet("#MainWidget{\n"
"   background-color: rgb(34, 34, 47);\n"
"}\n"
"\n"
"#Title{\n"
"   color: #fdfbfd;\n"
"}\n"
"\n"
"#TypeLabel{\n"
"   color: rgb(175, 175, 175);\n"
"}\n"
"\n"
"#FileLabel{\n"
"   color: rgb(175, 175, 175);\n"
"}\n"
"\n")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainWidget = QtWidgets.QWidget(Dialog)
        self.MainWidget.setObjectName("MainWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleWidget = QtWidgets.QWidget(self.MainWidget)
        self.TitleWidget.setObjectName("TitleWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.TitleWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Title = QtWidgets.QLabel(self.TitleWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.gridLayout_3.addWidget(self.Title, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.TitleWidget, 0, QtCore.Qt.AlignTop)
        self.ContentWidget = QtWidgets.QWidget(self.MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ContentWidget.sizePolicy().hasHeightForWidth())
        self.ContentWidget.setSizePolicy(sizePolicy)
        self.ContentWidget.setObjectName("ContentWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.ContentWidget)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.progressBar = QtWidgets.QProgressBar(self.ContentWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(253, 251, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.progressBar.setPalette(palette)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.ContentWidget)
        self.gridLayout.addWidget(self.MainWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Import Video"))
        self.Title.setText(_translate("Dialog", "Importing..."))


